commands = [
  { savefile_manager = "ctrl+o", feature = { visible = false, default = false } },
  { item_spawner = "ctrl+u", feature = { visible = false, default = false } },
  { character_stats = true, feature = { visible = false, default = false } },
  { warp = true, feature = { visible = true, default = false } },
  { cycle_speed = [0.5, 1.0, 2.0, 5.0, 10.0], feature = { visible = false, default = false } },
  { runes = 10000, feature = { visible = false, default = false } },
  { group = "Position storage", commands = [
    { nudge = 1.0, nudge_up = "[", nudge_down = "]", feature = { visible = false, default = false } },
    { position = "h", save = "rshift+h", feature = { visible = false, default = false } },
    { position = "j", save = "rshift+j", feature = { visible = false, default = false } },
    { position = "k", save = "rshift+k", feature = { visible = false, default = false } },
  ], feature = { visible = false, default = false }},
  { group = "Render flags", commands = [
    { cycle_color = [0, 1, 2, 3, 4, 5], feature = { visible = false, default = false } },
    { flag = "show_map", feature = { visible = false, default = false } },
    { flag = "show_chr", feature = { visible = false, default = false } },
    { flag = "display_stable_pos", feature = { visible = false, default = false } },
    { flag = "hitbox_high", feature = { visible = false, default = false } },
    { flag = "hitbox_low", feature = { visible = false, default = false } },
    { flag = "hitbox_f", feature = { visible = false, default = false } },
    { flag = "hitbox_character", feature = { visible = false, default = false } },
    { flag = "hitbox_event", feature = { visible = false, default = false } },
    { flags = ["weapon_hitbox1", "weapon_hitbox2", "weapon_hitbox3"], label = "Weapon hitboxes", feature = { visible = false, default = false } },
  ], feature = { visible = false, default = false }},
  { flag = "no_damage", feature = { visible = false, default = false } },
  { flag = "no_stamina_consume", feature = { visible = false, default = false } },
  { flags = ["no_fp_consume", "no_ashes_of_war_fp_consume"], label = "Inf Focus", feature = { visible = false, default = false } },
  { flags = ["no_goods_consume", "no_arrows_consume"], label = "Inf Consumables", feature = { visible = true, default = true } },
  { flag = "deathcam", feature = { visible = false, default = false } },
  { flag = "no_dead", feature = { visible = false, default = false } },
  { flag = "one_shot", feature = { visible = false, default = false } },
  { flag = "runearc", feature = { visible = true, default = false } },
  { target = "ctrl+n", feature = { visible = false, default = false } },
  { flags = ["field_area_direction", "field_area_altimeter", "field_area_compass"], label = "Field area HUD", feature = { visible = false, default = false } },
  { flag = "no_update_ai", feature = { visible = false, default = false } },
  { flag = "no_trigger_event", feature = { visible = false, default = false } },
  { flag = "gravity", feature = { visible = false, default = false } },
  { flag = "torrent_gravity", feature = { visible = false, default = false } },
  { flags = ["collision", "torrent_collision"], label = "No Collision", feature = { visible = false, default = false } },
  { flags = ["show_all_map_layers", "show_all_graces"], label="Show all graces/landmarks", feature = { visible = false, default = false } },
  { quitout = "p" },
]

radial-menu = [
  { key = "p", label = "Quitout" },
  { key = "rshift+h", label = "Save position" },
  { key = "h", label = "Load position" },
  { key = "ctrl+o", label = "Load savefile" },
]

[settings]
log_level = "INFO"
display = "f2"
hide = "rshift+f2"
dxgi_debug = false
show_console = true
radial_menu_open = "l3+r3"
indicators = [
  { indicator = "game_version", default = false, visible = true },
  { indicator = "igt", default = false, visible = false },
  { indicator = "position", default = false, visible = true },
  { indicator = "position_change", default = false, visible = false },
  { indicator = "animation", default = false, visible = false },
  { indicator = "fps", default = false, visible = false },
  { indicator = "framecount", default = false, visible = false },
  { indicator = "imgui_debug", default = false, visible = false }
]