commands = [
  { savefile_manager = "ctrl+o" },
  { item_spawner = "ctrl+u" },
  { character_stats = true },
  { warp = true },
  { cycle_speed = [0.5, 1.0, 2.0, 5.0, 10.0], hotkey = "8" },
  { runes = 10000, hotkey = "9" },
  { group = "Position storage", commands = [
    { nudge = 1.0, nudge_up = "[", nudge_down = "]" },
    { position = "h", save = "rshift+h" },
    { position = "j", save = "rshift+j" },
    { position = "k", save = "rshift+k" },
  ]},
  { group = "Render flags", commands = [
    { cycle_color = [0, 1, 2, 3, 4, 5] },
    { flag = "show_map", hotkey = "f4" },
    { flag = "show_chr", hotkey = "f5" },
    { flag = "display_stable_pos", hotkey = "f6" },
    { flag = "hitbox_high", hotkey = "f7" },
    { flag = "hitbox_low", hotkey = "f8" },
    { flag = "hitbox_f" },
    { flag = "hitbox_character" },
    { flag = "hitbox_event" },
    { flags = ["weapon_hitbox1", "weapon_hitbox2", "weapon_hitbox3"], hotkey = "f9", label = "Weapon hitboxes" },
  ]},

  { flag = "no_damage", hotkey = "1" },
  { flag = "no_stamina_consume", hotkey = "2" },
  { flags = ["no_fp_consume", "no_ashes_of_war_fp_consume"], hotkey = "3", label = "Inf Focus" },
  { flags = ["no_goods_consume", "no_arrows_consume"], hotkey = "4", label = "Inf Consumables" },
  { flag = "deathcam", hotkey = "5" },
  { flag = "no_dead", hotkey = "6" },
  { flag = "one_shot", hotkey = "7" },
  { flag = "runearc", hotkey = "o" },
  { target = "ctrl+n" },
  { flags = ["field_area_direction", "field_area_altimeter" , "field_area_compass"], label = "Field area HUD" },
  { flag = "no_update_ai", hotkey = "f1" },
  { flag = "no_trigger_event" },
  { flag = "gravity", hotkey = "f2" },
  { flag = "torrent_gravity", hotkey = "f2" },
  { flags = ["collision", "torrent_collision"], label = "No Collision" },
  { flags = ["show_all_map_layers", "show_all_graces"], hotkey = "f3", label="Show all graces/landmarks" },

  { quitout = "p" },
]

radial-menu = [
  { key = "p", label = "Quitout" },
  { key = "rshift+h", label = "Save position" },
  { key = "h", label = "Load position" },
  { key = "ctrl+o", label = "Load savefile" },
]

[settings]
log_level = "INFO"
display = "0"
hide = "rshift+0"
dxgi_debug = false
show_console = true
radial_menu_open = "l3+r3"
indicators = [
  { indicator = "game_version", default = false, visible = true },
  { indicator = "igt", default = false, visible = false },
  { indicator = "position", default = false, visible = true },
  { indicator = "position_change", default = false, visible = false },
  { indicator = "animation", default = false, visible = false },
  { indicator = "fps", default = false, visible = false },
  { indicator = "framecount", default = false, visible = false },
  { indicator = "imgui_debug", default = false, visible = false }
]
features = [
  { flag = "show_all_map_layers", visible = false, default = false },
  { flags = ["show_all_graces", "show_all_map_layers"], visible = false, default = false },
  { flag = "show_map", visible = false, default = false },
  { flag = "show_chr", visible = false, default = false },
  { flag = "display_stable_pos", visible = false, default = false },
  { flag = "hitbox_high", visible = true, default = false },
  { flag = "hitbox_low", visible = true, default = false },
  { flag = "hitbox_f", visible = true, default = false },
  { flag = "hitbox_character", visible = true, default = false },
  { flag = "hitbox_event", visible = true, default = false },
  { flags = ["weapon_hitbox1", "weapon_hitbox2", "weapon_hitbox3"], visible = true, default = false },
  { flag = "no_damage", visible = false, default = false },
  { flag = "no_stamina_consume", visible = false, default = false },
  { flags = ["no_fp_consume", "no_ashes_of_war_fp_consume"], visible = false, default = false },
  { flags = ["no_goods_consume", "no_arrows_consume"], visible = true, default = false },
  { flag = "deathcam", visible = false, default = false },
  { flag = "no_dead", visible = false, default = false },
  { flag = "one_shot", visible = false, default = false },
  { flag = "runearc", visible = true, default = false },
  { flags = ["field_area_direction", "field_area_altimeter", "field_area_compass"], visible = false, default = false },
  { flag = "no_update_ai", visible = false, default = false },
  { flag = "no_trigger_event", visible = false, default = false },
  { flag = "gravity", visible = false, default = false },
  { flag = "torrent_gravity", visible = false, default = false },
  { flags = ["collision", "torrent_collision"], visible = false, default = false },
  { group = "Render flags", visible = false, default = false},
  { group = "Position storage", visible = false, default = false}
]
